add-wheel-guide
ceramicstudio/js-composedb pull request #120
Opened 2023-05-09 19:28 UTC by JustinaPetr

# Wheel docs guide - #ADOPT-1200

## Description

Add wheel docs guide

2023-05-09 19:30 UTC, JustinaPetr commented
@3avi Before I spend more time polishing, wanted to get your thoughts on this structure.

One thought I have - would it make more sense to move `Wheel reference` as a subpage to Guides->Running Locally in favour of keeping Getting Started docs lean and stress-free?

2023-05-09 20:01 UTC, dbcfd requested changes

2023-05-09 20:01 UTC, dbcfd commented on website/versioned_docs/version-0.4.x/wheel-reference.mdx
> +In order to control the nodes connected to CAS (Ceramic Anchor Service), you will have to configure the authentication. This will allow
Link to page on what CAS auth means.

2023-05-09 20:01 UTC, dbcfd commented on website/versioned_docs/version-0.4.x/set-up-your-environment.mdx
> + you’d like to install to how your Ceramic node should be configured.
Should we mention something about help messages for prompts?

2023-05-09 20:42 UTC, 3avi approved these changes
besides danny's comments to include references to other docs pages like CAS, content looks good to me Justina, thanks for updating the sidebar + adding the wheel reference subpage.

2023-05-10 12:26 UTC, dbcfd submitted a review, later dismissed

2023-05-10 14:24 UTC, dbcfd approved these changes

2023-05-10 14:37 UTC, merged